#
# ============LICENSE_START==========================================
# org.onap.vvp/engagementmgr
# ===================================================================
# Copyright © 2017 AT&T Intellectual Property. All rights reserved.
# ===================================================================
#
# Unless otherwise specified, all software contained herein is licensed
# under the Apache License, Version 2.0 (the “License”);
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Unless otherwise specified, all documentation contained herein is licensed
# under the Creative Commons License, Attribution 4.0 Intl. (the “License”);
# you may not use this documentation except in compliance with the License.
# You may obtain a copy of the License at
#
#             https://creativecommons.org/licenses/by/4.0/
#
# Unless required by applicable law or agreed to in writing, documentation
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============LICENSE_END============================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementmanager', '0008_auto_20161009_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='state',
            field=models.CharField(
                choices=[
                    (b'(4,)',
                     b'approval'),
                    (b'(7,)',
                     b'archive'),
                    (b'(1,)',
                     b'automation'),
                    (b'(6,)',
                     b'closed'),
                    (b'(5,)',
                     b'handoff'),
                    (b'(3,)',
                     b'peer_review'),
                    (b'8',
                     b'pending'),
                    (b'(2,)',
                     b'review')],
                default=b'pending',
                max_length=36),
        ),
        migrations.AlterField(
            model_name='recentengagement',
            name='action_type',
            field=models.CharField(
                choices=[
                    (b'(3,)',
                     b'GOT_OWNERSHIP_OVER_ENGAGEMENT'),
                    (b'(1,)',
                     b'JOINED_TO_ENGAGEMENT'),
                    (b'(4,)',
                     b'NAVIGATED_INTO_ENGAGEMENT'),
                    (b'(5,)',
                     b'NEW_VF_CREATED'),
                    (b'(2,)',
                     b'NEXT_STEP_ASSIGNED')],
                max_length=36),
        ),
    ]
