#  
# ============LICENSE_START========================================== 
# org.onap.vvp/engagementmgr
# ===================================================================
# Copyright © 2017 AT&T Intellectual Property. All rights reserved.
# ===================================================================
#
# Unless otherwise specified, all software contained herein is licensed
# under the Apache License, Version 2.0 (the “License”);
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Unless otherwise specified, all documentation contained herein is licensed
# under the Creative Commons License, Attribution 4.0 Intl. (the “License”);
# you may not use this documentation except in compliance with the License.
# You may obtain a copy of the License at
#
#             https://creativecommons.org/licenses/by/4.0/
#
# Unless required by applicable law or agreed to in writing, documentation
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============LICENSE_END============================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-25 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementmanager', '0009_auto_20161018_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[(b'change_checklist_state', b'change_checklist_state'), (b'eng_validation_request', b'eng_validation_request'), (
                b'next_steps', b'next_steps'), (b'ssh_key_added', b'ssh_key_added'), (b'user_joined_eng', b'user_joined_eng'), (b'vfc', b'vfc')], max_length=36),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='state',
            field=models.CharField(choices=[(b'approval', b'approval'), (b'archive', b'archive'), (b'automation', b'automation'), (b'closed', b'closed'), (
                b'handoff', b'handoff'), (b'peer_review', b'peer_review'), (b'pending', b'pending'), (b'review', b'review')], default=b'pending', max_length=36),
        ),
        migrations.AlterField(
            model_name='checklistdecision',
            name='peer_review_value',
            field=models.CharField(choices=[(b'approved', b'approved'), (b'denied', b'denied'),
                                            (b'na', b'na'), (b'not_relevant', b'not_relevant')], max_length=36),
        ),
        migrations.AlterField(
            model_name='checklistdecision',
            name='review_value',
            field=models.CharField(choices=[(b'approved', b'approved'), (b'denied', b'denied'),
                                            (b'na', b'na'), (b'not_relevant', b'not_relevant')], max_length=36),
        ),
        migrations.AlterField(
            model_name='checklistlineitem',
            name='line_type',
            field=models.CharField(choices=[(b'auto', b'auto'), (b'manual', b'manual')],
                                   default=b'auto', max_length=36),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='category',
            field=models.CharField(choices=[(b'glance', b'glance'), (b'heat', b'heat'),
                                            (b'overall', b'overall')], default=b'overall', max_length=36),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='starred_engagement',
            field=models.ManyToManyField(blank=True, to='engagementmanager.IceUser'),
        ),
        migrations.AlterField(
            model_name='nextstep',
            name='next_step_type',
            field=models.CharField(choices=[(b'add_contact_person', b'add_contact_person'), (b'el_handoff', b'el_handoff'), (b'set_ssh', b'set_ssh'), (
                b'submit_vf_package', b'submit_vf_package'), (b'trial_agreements', b'trial_agreements'), (b'user_defined', b'user_defined')], default=b'user_defined', max_length=36),
        ),
        migrations.AlterField(
            model_name='recentengagement',
            name='action_type',
            field=models.CharField(choices=[(b'GOT_OWNERSHIP_OVER_ENGAGEMENT', b'GOT_OWNERSHIP_OVER_ENGAGEMENT'), (b'JOINED_TO_ENGAGEMENT', b'JOINED_TO_ENGAGEMENT'), (
                b'NAVIGATED_INTO_ENGAGEMENT', b'NAVIGATED_INTO_ENGAGEMENT'), (b'NEW_VF_CREATED', b'NEW_VF_CREATED'), (b'NEXT_STEP_ASSIGNED', b'NEXT_STEP_ASSIGNED')], max_length=36),
        ),
    ]
