#  
# ============LICENSE_START========================================== 
# org.onap.vvp/engagementmgr
# ===================================================================
# Copyright © 2017 AT&T Intellectual Property. All rights reserved.
# ===================================================================
#
# Unless otherwise specified, all software contained herein is licensed
# under the Apache License, Version 2.0 (the “License”);
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Unless otherwise specified, all documentation contained herein is licensed
# under the Creative Commons License, Attribution 4.0 Intl. (the “License”);
# you may not use this documentation except in compliance with the License.
# You may obtain a copy of the License at
#
#             https://creativecommons.org/licenses/by/4.0/
#
# Unless required by applicable law or agreed to in writing, documentation
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============LICENSE_END============================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.
# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-28 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('engagementmanager', '0012_auto_20161109_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagement',
            name='active_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='active time'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='aic_instantiation_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='aic instantiation time'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='asdc_onboarding_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='asdc onboarding time'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='completed_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='completed time'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='heat_validated_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='heat validated time'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='image_scan_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='image scan time'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='intake_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='intake time'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='started_state_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='started state time'),
        ),
        migrations.AddField(
            model_name='engagement',
            name='validated_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='validated time'),
        ),
    ]
