#  
# ============LICENSE_START========================================== 
# org.onap.vvp/engagementmgr
# ===================================================================
# Copyright © 2017 AT&T Intellectual Property. All rights reserved.
# ===================================================================
#
# Unless otherwise specified, all software contained herein is licensed
# under the Apache License, Version 2.0 (the “License”);
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Unless otherwise specified, all documentation contained herein is licensed
# under the Creative Commons License, Attribution 4.0 Intl. (the “License”);
# you may not use this documentation except in compliance with the License.
# You may obtain a copy of the License at
#
#             https://creativecommons.org/licenses/by/4.0/
#
# Unless required by applicable law or agreed to in writing, documentation
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============LICENSE_END============================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.
# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagementmanager', '0022_auto_20170118_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='activation_token_create_time',
        ),
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='iceuserprofile',
            name='temp_password',
        ),
        migrations.AlterField(
            model_name='iceuserprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='engagementmanager.Vendor'),
        ),
        migrations.AlterField(
            model_name='iceuserprofile',
            name='is_att_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='iceuserprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='engagementmanager.Role'),
        ),
        migrations.AlterField(
            model_name='iceuserprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engagementmanager.CustomUser'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='ice_custom_user',
        ),
    ]
