#  
# ============LICENSE_START========================================== 
# org.onap.vvp/engagementmgr
# ===================================================================
# Copyright © 2017 AT&T Intellectual Property. All rights reserved.
# ===================================================================
#
# Unless otherwise specified, all software contained herein is licensed
# under the Apache License, Version 2.0 (the “License”);
# you may not use this software except in compliance with the License.
# You may obtain a copy of the License at
#
#             http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#
#
# Unless otherwise specified, all documentation contained herein is licensed
# under the Creative Commons License, Attribution 4.0 Intl. (the “License”);
# you may not use this documentation except in compliance with the License.
# You may obtain a copy of the License at
#
#             https://creativecommons.org/licenses/by/4.0/
#
# Unless required by applicable law or agreed to in writing, documentation
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# ============LICENSE_END============================================
#
# ECOMP is a trademark and service mark of AT&T Intellectual Property.
# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagementmanager', '0027_add_version_to_vf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('user_joined_eng', 'user_joined_eng'), ('ssh_key_added', 'ssh_key_added'), ('eng_validation_request', 'eng_validation_request'), ('next_steps', 'next_steps'), ('vfc', 'vfc'), (
                'change_checklist_state', 'change_checklist_state'), ('vf_provisioing_event', 'vf_provisioing_event'), ('test_finished_event', 'test_finished_event'), ('change_engagement_stage', 'change_engagement_stage')], max_length=36),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='state',
            field=models.CharField(choices=[('automation', 'automation'), ('review', 'review'), ('peer_review', 'peer_review'), ('approval', 'approval'), (
                'handoff', 'handoff'), ('closed', 'closed'), ('archive', 'archive'), ('pending', 'pending')], default='pending', max_length=36),
        ),
        migrations.AlterField(
            model_name='checklistdecision',
            name='peer_review_value',
            field=models.CharField(choices=[('approved', 'approved'), ('denied', 'denied'),
                                            ('not_relevant', 'not_relevant'), ('na', 'na')], max_length=36),
        ),
        migrations.AlterField(
            model_name='checklistdecision',
            name='review_value',
            field=models.CharField(choices=[('approved', 'approved'), ('denied', 'denied'),
                                            ('not_relevant', 'not_relevant'), ('na', 'na')], max_length=36),
        ),
        migrations.AlterField(
            model_name='checklistlineitem',
            name='line_type',
            field=models.CharField(choices=[('auto', 'auto'), ('manual', 'manual')], default='auto', max_length=36),
        ),
        migrations.AlterField(
            model_name='checklisttemplate',
            name='category',
            field=models.CharField(choices=[('overall', 'overall'), ('heat', 'heat'), ('glance', 'glance'),
                                            ('instantiation', 'instantiation'), ('asdc', 'asdc')], default='overall', max_length=36),
        ),
        migrations.AlterField(
            model_name='engagement',
            name='engagement_stage',
            field=models.CharField(choices=[('Intake', 'Intake'), ('Active', 'Active'), ('Validated', 'Validated'), (
                'Completed', 'Completed'), ('Archived', 'Archived')], db_index=True, default='Intake', max_length=15),
        ),
        migrations.AlterField(
            model_name='nextstep',
            name='next_step_type',
            field=models.CharField(choices=[('set_ssh', 'set_ssh'), ('trial_agreements', 'trial_agreements'), ('add_contact_person', 'add_contact_person'), (
                'submit_vf_package', 'submit_vf_package'), ('el_handoff', 'el_handoff'), ('user_defined', 'user_defined')], default='user_defined', max_length=36),
        ),
        migrations.AlterField(
            model_name='nextstep',
            name='state',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Completed', 'Completed')], max_length=15),
        ),
        migrations.AlterField(
            model_name='recentengagement',
            name='action_type',
            field=models.CharField(choices=[('JOINED_TO_ENGAGEMENT', 'JOINED_TO_ENGAGEMENT'), ('NEXT_STEP_ASSIGNED', 'NEXT_STEP_ASSIGNED'), ('GOT_OWNERSHIP_OVER_ENGAGEMENT',
                                                                                                                                             'GOT_OWNERSHIP_OVER_ENGAGEMENT'), ('NAVIGATED_INTO_ENGAGEMENT', 'NAVIGATED_INTO_ENGAGEMENT'), ('NEW_VF_CREATED', 'NEW_VF_CREATED')], max_length=36),
        ),
    ]
